# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: auth/auth.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class LoginRequest(betterproto.Message):
    username: str = betterproto.string_field(1)
    password: str = betterproto.string_field(2)


@dataclass
class AuthResponse(betterproto.Message):
    token: str = betterproto.string_field(1)


@dataclass
class SignupRequest(betterproto.Message):
    username: str = betterproto.string_field(1)
    email: str = betterproto.string_field(2)
    password: str = betterproto.string_field(3)


class AuthStub(betterproto.ServiceStub):
    async def login(self, *, username: str = "", password: str = "") -> AuthResponse:
        """Authentication"""

        request = LoginRequest()
        request.username = username
        request.password = password

        return await self._unary_unary(
            "/auth.Auth/Login",
            request,
            AuthResponse,
        )

    async def sign_up(
        self, *, username: str = "", email: str = "", password: str = ""
    ) -> AuthResponse:
        request = SignupRequest()
        request.username = username
        request.email = email
        request.password = password

        return await self._unary_unary(
            "/auth.Auth/SignUp",
            request,
            AuthResponse,
        )
