# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: common/common.proto, common/payment_plan.proto, common/payment_task.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import List

import betterproto


class DELETE_STATUS(betterproto.Enum):
    """Status message for Delete database action"""

    DELETE_STATUS_UNKNOWN = 0
    DELETE_STATUS_PENDING = 1
    DELETE_STATUS_IN_PROGRESS = 2
    DELETE_STATUS_SUCCESS = 3
    DELETE_STATUS_FAILED = 4


class PlanType(betterproto.Enum):
    """Different optimization plans that a PaymentPlan may prioritize"""

    PLAN_TYPE_UNKNOWN = 0
    PLAN_TYPE_OPTIM_CREDIT_SCORE = 1
    PLAN_TYPE_MIN_FEES = 2


class PaymentFrequency(betterproto.Enum):
    """Payment frequency for a PaymentPlan"""

    PAYMENT_FREQUENCY_UNKNOWN = 0
    PAYMENT_FREQUENCY_WEEKLY = 1
    PAYMENT_FREQUENCY_BIWEEKLY = 2
    PAYMENT_FREQUENCY_MONTHLY = 3
    PAYMENT_FREQUENCY_QUARTERLY = 4


class PaymentStatus(betterproto.Enum):
    PAYMENT_STATUS_UNKNOWN = 0
    # Payment plan is in good standing and all payments are current
    PAYMENT_STATUS_CURRENT = 1
    # This plan is fully paid
    PAYMENT_STATUS_COMPLETED = 2
    # The user has requested this payment to be cancelled
    PAYMENT_STATUS_CANCELLED = 3
    # The payment plan is not current because the user has missed a payment and
    # still have not paid it
    PAYMENT_STATUS_IN_DEFAULT = 4


class PaymentActionStatus(betterproto.Enum):
    PAYMENT_ACTION_STATUS_UNKNOWN = 0
    # Payment is pending
    PAYMENT_ACTION_STATUS_PENDING = 1
    # payment is completed
    PAYMENT_ACTION_STATUS_COMPLETED = 2
    # payment defaulted
    PAYMENT_ACTION_STATUS_IN_DEFAULT = 3


@dataclass
class PaymentAction(betterproto.Message):
    # account to which payment shall be made
    account_id: str = betterproto.string_field(1)
    # amount of payment
    amount: float = betterproto.float_field(2)
    # Planned date of transaction
    transaction_date: datetime = betterproto.message_field(3)
    # status of payment action
    status: "PaymentActionStatus" = betterproto.enum_field(4)


@dataclass
class PaymentPlan(betterproto.Message):
    payment_plan_id: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)
    payment_task_id: List[str] = betterproto.string_field(3)
    timeline: float = betterproto.float_field(4)
    payment_freq: "PaymentFrequency" = betterproto.enum_field(5)
    amount_per_payment: float = betterproto.float_field(6)
    plan_type: "PlanType" = betterproto.enum_field(7)
    # Expected date the plan should be completed
    end_date: datetime = betterproto.message_field(8)
    # This Payment plan has not completed and is still active
    active: bool = betterproto.bool_field(9)
    # Current status of this plan
    status: "PaymentStatus" = betterproto.enum_field(10)
    # payment actions of the plan
    payment_action: List["PaymentAction"] = betterproto.message_field(11)


@dataclass
class PaymentTask(betterproto.Message):
    """
    PaymentTask encapsulates the payment goals a user has per credit account
    """

    payment_task_id: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)
    account_id: str = betterproto.string_field(4)
    amount: float = betterproto.double_field(5)


@dataclass
class PaymentPlanResponse(betterproto.Message):
    """Response for CreatePaymentPlan"""

    payment_plans: List["PaymentPlan"] = betterproto.message_field(1)


@dataclass
class UpdatePaymentPlanPlanRequest(betterproto.Message):
    """Request for UpdatePaymentPlanPlan"""

    payment_plans: List["PaymentPlan"] = betterproto.message_field(1)
    meta_data: "MetaData" = betterproto.message_field(2)


@dataclass
class MetaData(betterproto.Message):
    """
    MetaData is any preferences a user may have regarding how a payment task
    should be incorporated into a Payment Plan
    """

    preferred_plan_type: "PlanType" = betterproto.enum_field(1)
    preferred_timeline_in_months: float = betterproto.double_field(2)
    preferred_payment_freq: "PaymentFrequency" = betterproto.enum_field(3)
