# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: common/common.proto, common/payment_task.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from .google import protobuf


class DELETE_STATUS(betterproto.Enum):
    """Status message for Delete database action"""

    DELETE_STATUS_UNKNOWN = 0
    DELETE_STATUS_PENDING = 1
    DELETE_STATUS_IN_PROGRESS = 2
    DELETE_STATUS_SUCCESS = 3
    DELETE_STATUS_FAILED = 4


class PlanType(betterproto.Enum):
    """Different optimization plans that a PaymentPlan may prioritize"""

    PLAN_TYPE_UNKNOWN = 0
    PLAN_TYPE_OPTIM_CREDIT_SCORE = 1
    PLAN_TYPE_MIN_FEES = 2


class PaymentFrequency(betterproto.Enum):
    """Payment frequency for a PaymentPlan"""

    PAYMENT_FREQUENCY_UNKNOWN = 0
    PAYMENT_FREQUENCY_WEEKLY = 1
    PAYMENT_FREQUENCY_BIWEEKLY = 2
    PAYMENT_FREQUENCY_MONTHLY = 3
    PAYMENT_FREQUENCY_QUARTERLY = 4


@dataclass
class PaymentTask(betterproto.Message):
    """
    PaymentTask encapsulates the payment goals a user has per credit account
    """

    payment_task_id: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)
    account_id: str = betterproto.string_field(4)
    amount: float = betterproto.double_field(5)


@dataclass
class MetaData(betterproto.Message):
    """
    MetaData is any preferences a user may have regarding how a payment task
    should be incorporated into a Payment Plan
    """

    preferred_plan_type: "PlanType" = betterproto.enum_field(1)
    timeline_in_months: float = betterproto.float_field(2)
    preferred_payment_freq: "PaymentFrequency" = betterproto.enum_field(3)


@dataclass
class CreatePaymentTaskRequest(betterproto.Message):
    """CRUD Methods"""

    payment_task: "PaymentTask" = betterproto.message_field(1)


@dataclass
class GetPaymentTaskRequest(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass
class UpdatePaymentTaskRequest(betterproto.Message):
    id: str = betterproto.string_field(1)
    payment_task: "PaymentTask" = betterproto.message_field(2)
    mask: protobuf.FieldMask = betterproto.message_field(3)


@dataclass
class DeletePaymentTaskRequest(betterproto.Message):
    id: str = betterproto.string_field(1)


@dataclass
class ListPaymentTaskRequest(betterproto.Message):
    pass


@dataclass
class ListPaymentTaskResponse(betterproto.Message):
    payment_tasks: List["PaymentTask"] = betterproto.message_field(1)


@dataclass
class DeletePaymentTaskResponse(betterproto.Message):
    status: "DELETE_STATUS" = betterproto.enum_field(1)
    payment_task: "PaymentTask" = betterproto.message_field(2)


@dataclass
class CreateManyPaymentTaskRequest(betterproto.Message):
    payment_tasks: List["PaymentTask"] = betterproto.message_field(1)


@dataclass
class CreateManyPaymentTaskResponse(betterproto.Message):
    pass
