# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: planning/payment_plan.proto, planning/planning.proto
# plugin: python-betterproto
from dataclasses import dataclass
from datetime import datetime
from typing import List

import betterproto

from . import common


class PaymentStatus(betterproto.Enum):
    PAYMENT_STATUS_UNKNOWN = 0
    # Payment plan is in good standing and all payments are current
    PAYMENT_STATUS_CURRENT = 1
    # This plan is fully paid
    PAYMENT_STATUS_COMPLETED = 2
    # The user has requested this payment to be cancelled
    PAYMENT_STATUS_CANCELLED = 3
    # The payment plan is not current because the user has missed a payment and
    # still have not paid it
    PAYMENT_STATUS_IN_DEFAULT = 4


class PaymentActionStatus(betterproto.Enum):
    PAYMENT_ACTION_STATUS_UNKNOWN = 0
    # Payment is pending
    PAYMENT_ACTION_STATUS_PENDING = 1
    # payment is completed
    PAYMENT_ACTION_STATUS_COMPLETED = 2
    # payment defaulted
    PAYMENT_ACTION_STATUS_IN_DEFAULT = 3


@dataclass
class PaymentAction(betterproto.Message):
    # account to which payment shall be made
    account_id: str = betterproto.string_field(1)
    # amount of payment
    amount: float = betterproto.float_field(2)
    # Planned date of transaction
    transaction_date: datetime = betterproto.message_field(3)
    # status of payment action
    status: "PaymentActionStatus" = betterproto.enum_field(4)


@dataclass
class PaymentPlan(betterproto.Message):
    payment_plan_id: str = betterproto.string_field(1)
    user_id: str = betterproto.string_field(2)
    payment_task_id: List[str] = betterproto.string_field(3)
    timeline: float = betterproto.float_field(4)
    payment_freq: common.PaymentFrequency = betterproto.enum_field(5)
    amount_per_payment: float = betterproto.float_field(6)
    plan_type: common.PlanType = betterproto.enum_field(7)
    # Expected date the plan should be completed
    end_date: datetime = betterproto.message_field(8)
    # This Payment plan has not completed and is still active
    active: bool = betterproto.bool_field(9)
    # Current status of this plan
    status: "PaymentStatus" = betterproto.enum_field(10)
    # payment actions of the plan
    payment_action: List["PaymentAction"] = betterproto.message_field(11)

