# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_task.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payment_task.proto',
  package='planning',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12payment_task.proto\x12\x08planning\"\x8a\x01\n\x0bPaymentTask\x12\x17\n\x0fpayment_task_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x16\n\x0etransaction_id\x18\x03 \x01(\x05\x12\x12\n\naccount_id\x18\x04 \x01(\x05\x12%\n\tmeta_data\x18\x05 \x01(\x0b\x32\x12.planning.MetaData\"\x93\x01\n\x08MetaData\x12/\n\x13preferred_plan_type\x18\x01 \x01(\x0e\x32\x12.planning.PlanType\x12\x1a\n\x12preferred_timeline\x18\x02 \x01(\x01\x12:\n\x16preferred_payment_freq\x18\x03 \x01(\x0e\x32\x1a.planning.PaymentFrequency*F\n\x08PlanType\x12\x14\n\x10PLANTYPE_UNKNOWN\x10\x00\x12\x16\n\x12OPTIM_CREDIT_SCORE\x10\x01\x12\x0c\n\x08MIN_FEES\x10\x02*a\n\x10PaymentFrequency\x12\x17\n\x13PAYMENTFREQ_UNKNOWN\x10\x00\x12\n\n\x06WEEKLY\x10\x01\x12\x0c\n\x08\x42IWEEKLY\x10\x02\x12\x0b\n\x07MONTHLY\x10\x03\x12\r\n\tQUARTERLY\x10\x04\x62\x06proto3'
)

_PLANTYPE = _descriptor.EnumDescriptor(
  name='PlanType',
  full_name='planning.PlanType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLANTYPE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPTIM_CREDIT_SCORE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MIN_FEES', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=323,
  serialized_end=393,
)
_sym_db.RegisterEnumDescriptor(_PLANTYPE)

PlanType = enum_type_wrapper.EnumTypeWrapper(_PLANTYPE)
_PAYMENTFREQUENCY = _descriptor.EnumDescriptor(
  name='PaymentFrequency',
  full_name='planning.PaymentFrequency',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PAYMENTFREQ_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WEEKLY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BIWEEKLY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MONTHLY', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='QUARTERLY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=395,
  serialized_end=492,
)
_sym_db.RegisterEnumDescriptor(_PAYMENTFREQUENCY)

PaymentFrequency = enum_type_wrapper.EnumTypeWrapper(_PAYMENTFREQUENCY)
PLANTYPE_UNKNOWN = 0
OPTIM_CREDIT_SCORE = 1
MIN_FEES = 2
PAYMENTFREQ_UNKNOWN = 0
WEEKLY = 1
BIWEEKLY = 2
MONTHLY = 3
QUARTERLY = 4



_PAYMENTTASK = _descriptor.Descriptor(
  name='PaymentTask',
  full_name='planning.PaymentTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='payment_task_id', full_name='planning.PaymentTask.payment_task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='planning.PaymentTask.user_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transaction_id', full_name='planning.PaymentTask.transaction_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='planning.PaymentTask.account_id', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='meta_data', full_name='planning.PaymentTask.meta_data', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=171,
)


_METADATA = _descriptor.Descriptor(
  name='MetaData',
  full_name='planning.MetaData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='preferred_plan_type', full_name='planning.MetaData.preferred_plan_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preferred_timeline', full_name='planning.MetaData.preferred_timeline', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='preferred_payment_freq', full_name='planning.MetaData.preferred_payment_freq', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=321,
)

_PAYMENTTASK.fields_by_name['meta_data'].message_type = _METADATA
_METADATA.fields_by_name['preferred_plan_type'].enum_type = _PLANTYPE
_METADATA.fields_by_name['preferred_payment_freq'].enum_type = _PAYMENTFREQUENCY
DESCRIPTOR.message_types_by_name['PaymentTask'] = _PAYMENTTASK
DESCRIPTOR.message_types_by_name['MetaData'] = _METADATA
DESCRIPTOR.enum_types_by_name['PlanType'] = _PLANTYPE
DESCRIPTOR.enum_types_by_name['PaymentFrequency'] = _PAYMENTFREQUENCY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PaymentTask = _reflection.GeneratedProtocolMessageType('PaymentTask', (_message.Message,), {
  'DESCRIPTOR' : _PAYMENTTASK,
  '__module__' : 'payment_task_pb2'
  # @@protoc_insertion_point(class_scope:planning.PaymentTask)
  })
_sym_db.RegisterMessage(PaymentTask)

MetaData = _reflection.GeneratedProtocolMessageType('MetaData', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'payment_task_pb2'
  # @@protoc_insertion_point(class_scope:planning.MetaData)
  })
_sym_db.RegisterMessage(MetaData)


# @@protoc_insertion_point(module_scope)
